/**
 * @fileoverview gRPC-Web generated client stub for room
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.3
// source: room.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.room = require('./room_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.room.UserInRoomDataControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.room.UserInRoomDataControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.room.UserInRoomDataListRequest,
 *   !proto.room.UserInRoomData>}
 */
const methodDescriptor_UserInRoomDataController_List = new grpc.web.MethodDescriptor(
  '/room.UserInRoomDataController/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.room.UserInRoomDataListRequest,
  proto.room.UserInRoomData,
  /**
   * @param {!proto.room.UserInRoomDataListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.room.UserInRoomData.deserializeBinary
);


/**
 * @param {!proto.room.UserInRoomDataListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.room.UserInRoomData>}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/room.UserInRoomDataController/List',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_List);
};


/**
 * @param {!proto.room.UserInRoomDataListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.room.UserInRoomData>}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/room.UserInRoomDataController/List',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.room.UserInRoomData,
 *   !proto.room.UserInRoomData>}
 */
const methodDescriptor_UserInRoomDataController_Create = new grpc.web.MethodDescriptor(
  '/room.UserInRoomDataController/Create',
  grpc.web.MethodType.UNARY,
  proto.room.UserInRoomData,
  proto.room.UserInRoomData,
  /**
   * @param {!proto.room.UserInRoomData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.room.UserInRoomData.deserializeBinary
);


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.room.UserInRoomData)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.room.UserInRoomData>|undefined}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/room.UserInRoomDataController/Create',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Create,
      callback);
};


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.room.UserInRoomData>}
 *     Promise that resolves to the response
 */
proto.room.UserInRoomDataControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/room.UserInRoomDataController/Create',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.room.UserInRoomDataRetrieveRequest,
 *   !proto.room.UserInRoomData>}
 */
const methodDescriptor_UserInRoomDataController_Retrieve = new grpc.web.MethodDescriptor(
  '/room.UserInRoomDataController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.room.UserInRoomDataRetrieveRequest,
  proto.room.UserInRoomData,
  /**
   * @param {!proto.room.UserInRoomDataRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.room.UserInRoomData.deserializeBinary
);


/**
 * @param {!proto.room.UserInRoomDataRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.room.UserInRoomData)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.room.UserInRoomData>|undefined}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/room.UserInRoomDataController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Retrieve,
      callback);
};


/**
 * @param {!proto.room.UserInRoomDataRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.room.UserInRoomData>}
 *     Promise that resolves to the response
 */
proto.room.UserInRoomDataControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/room.UserInRoomDataController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.room.UserInRoomData,
 *   !proto.room.UserInRoomData>}
 */
const methodDescriptor_UserInRoomDataController_Update = new grpc.web.MethodDescriptor(
  '/room.UserInRoomDataController/Update',
  grpc.web.MethodType.UNARY,
  proto.room.UserInRoomData,
  proto.room.UserInRoomData,
  /**
   * @param {!proto.room.UserInRoomData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.room.UserInRoomData.deserializeBinary
);


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.room.UserInRoomData)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.room.UserInRoomData>|undefined}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/room.UserInRoomDataController/Update',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Update,
      callback);
};


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.room.UserInRoomData>}
 *     Promise that resolves to the response
 */
proto.room.UserInRoomDataControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/room.UserInRoomDataController/Update',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.room.UserInRoomData,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_UserInRoomDataController_Destroy = new grpc.web.MethodDescriptor(
  '/room.UserInRoomDataController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.room.UserInRoomData,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.room.UserInRoomData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.room.UserInRoomDataControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/room.UserInRoomDataController/Destroy',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Destroy,
      callback);
};


/**
 * @param {!proto.room.UserInRoomData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.room.UserInRoomDataControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/room.UserInRoomDataController/Destroy',
      request,
      metadata || {},
      methodDescriptor_UserInRoomDataController_Destroy);
};


module.exports = proto.room;

